name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to gh-pages
        run: |
          mkdir -p deploy
          cp -r selfless-ce-mbale-repo/* deploy/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
