name = "selfless-ce-backend"
main = "worker.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "selfless_finance"
database_id = "480d9b6a-1515-45b1-a425-16821b071fc0"